### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by Tooconfident** [lcanderson/prj-rev-bwfs-tea-cozy#4]
https://github.com/lcanderson/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/style.css#L42

This looks really good, you can actually apply this as a universal class to multiple sections of this project, but this is great as is, good job!

**Comment by lcanderson** [comment]
Ok, now you are just getting fancy on me.  :)  I will check into what a universal class is.  Thanks.
