### ISSUE TITLE
Summary 

### ISSUE THREAD

**Issue by Tooconfident** [lcanderson/prj-rev-bwfs-tea-cozy#5]
Grade: Meets Expectations

Good job with this project. I really didn't have any major criticism or preferences on changing your decisions. I really liked your choices and you show a solid knowledge of flex and other complex css properties like z-index. You will see my line issue's are more commentary on alternative solutions to your style choices. Whether you think they are better or helpful is up to you. I hope you find them nice options to clean things up and make it DRY(Don't Repeat Yourself). Start looking into media queries for responsive design websites. You are totally ready for making your website mobile friendly and getting a head start on that will help you going forward. Great work!

https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by lcanderson** [comment]
Nice feedback.  I had not heard the DRY acronym before.  I like it and will keep it in mind.  I struggled with this project and had to do a lot of research.  I borrowed heavily from what I saw on other websites.  My knowledge is anything but solid, however, I do appreciate the pep talk.  Thank you.
